name: Build & Deploy Angular to dkeshri.github.io

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: web-app

      - name: Build Angular
        run: npm run build -- --configuration production --base-href /
        working-directory: web-app

      - name: Clone target repo (dkeshri.github.io)
        run: |
          git clone https://x-access-token:${{ secrets.code_push }}@github.com/dkeshri/dkeshri.github.io.git deploy-repo

      - name: Copy build files
        run: |
          rm -rf deploy-repo/*
          cp -r web-app/dist/web-app/browser/* deploy-repo/

      - name: Commit & push to GitHub Pages repo
        run: |
          cd deploy-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Deploy Angular app" || echo "No changes"
          git push origin main
